services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  MarketingPlanBundle\AdminMenu: ~

  # 如果确认要使用自动扫描、自动注册，建议尽可能将要扫描的目录路径收缩，不要设置那么大的范围
  MarketingPlanBundle\Command\:
    resource: '../../Command/'
  MarketingPlanBundle\Controller\:
    resource: '../../Controller/'
  MarketingPlanBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  MarketingPlanBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  MarketingPlanBundle\Procedure\:
    resource: '../../Procedure/'
  MarketingPlanBundle\Repository\:
    resource: '../../Repository/'
  MarketingPlanBundle\Service\:
    resource: '../../Service/'
